<?php
require './templates/task/header.phtml';
?>
<div class="mt-1 w-100 mx-auto" style="height: 300px;">
    <table class="table">
        <thead>
            <tr>
                <th class="text-center">Pelicula</th>
                <th class="text-center">Duracion</th>
                <th class="text-center">Genero</th>
                <th class="text-center">Descripcion</th>
                <th class="text-center">Fecha de estreno </th>
                <th class="text-center">publico </th>
                <th class="text-center">Imagen </th>
                <th class="text-center">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($lista as $item) { ?>
                <tr>
                    <td class="text-center"><?= $item->id_pelicula; ?></td>
                    <td class="text-center"><?= $item->nombre_pelicula; ?></td>
                    <td class="text-center"><?= $item->duracion; ?></td>
                    <td class="text-center"><?= $item->genero; ?></td>
                    <td class="text-center"><?= $item->descripcion; ?></td>
                    <td class="text-center"><?= $item->fecha_estreno; ?></td>
                    <td class="text-center"><?= $item->publico; ?></td>
                    <td class="text-center"><img src="<?= $item->img; ?>" class="img" style="max-width: 80px"></td>
                    <td class="text-center">
                        <a href="listaId/<?= $item->id_pelicula;?>" class="btn btn-primary">Ver Pelicula</a>
                        <?php if ($adm) { ?>
                            <a href="eliminar_pelicula/<?= $item->id_pelicula; ?>" type="button" class='btn btn-danger ml-auto'>Eliminar</a>
                            <a href="modificar_pelicula_formulario/<?= $item->id_pelicula; ?>" type="button" class='btn btn-success ml-auto'>Modificar</a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php
 require_once 'templates/task/footer.phtml';
