<?php require './templates/task/header.phtml'; ?>

    <div class="container mt-5">
        <?php  foreach($actor as $cat) { ?>
            
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="<?= $cat->img; ?>" class="img-fluid rounded-start" alt="Imagen del Producto">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title"><?= $cat->nombreProducto; ?></h5>
                            <p class="card-text"><?= $cat->idCodigoProducto; ?></p>
                            <p class="card-text"><strong>Precio:</strong>$<?= $cat->precio; ?></p>
                            <p class="card-text"><strong>Marca:</strong> <?= $cat->marca; ?></p>
                            <p class="card-text"><strong>Categoría:</strong> <?= $cat->actor; ?></p>
                            <a href="actor" class="btn btn-primary">Volver</a>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>

<?php require_once 'templates/task/footer.phtml'; ?>