<?php

   require './templates/task/header.phtml';?>
    
    <div class="container mt-5">

        <h2>Modificacion de actor</h2>
        <form action="modificar_actor" method="POST">
            
            <div class="mb-3">
                <input type="hidden" class="form-control" id="id_actor" name="id_actor" value="<?=$actor[0]->id_actor?>">
            </div>
            <div class="mb-3">
                <label for="nombre_actor" class="form-label">Nombre del actor</label>
                <input type="text" class="form-control" id="material" name="material" value="<?=$actor[0]->nombre_actor;?>" required>
            </div>
            <div class="mb-3">
                <label for="fecha_nacimiento" class="form-label">Fecha de nacimiento </label>
                <input type="date" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" value="<?=$actor[0]->fecha_nacimiento;?>"required>
            </div>
            <div class="mb-3">
                <label for="nacionalidad" class="form-label">nacionalidad</label>
                <input type="text" class="form-control" id="nacionalidad" name="nacionalidad" value="<?=$actor[0]->nacionalidad;?>"required>
            </div>
 
            <button type="submit" class="btn btn-primary">Modificar</button>
        </form>
    </div>

    <?php

    require_once 'templates/task/footer.phtml'; 
