<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL; ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <title>TUDAI -Trabajo WEB</title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <?php if (!AuthHelper::isAdmin()) : //si no esta logueado va a mostrarse login?>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="login">Login</a>
          </li>
          <li class="nav-item active">
          <a class="nav-link" href="lista">listaado <span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
           <a class="nav-link" href="actor">actores</a>
          </li>
          <?php else : ?>
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_EMAIL'] ?>)</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="agregar_pelicula_formulario">Agregar items</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="lista">Gestion items</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="agregar_actor_formulario">Agregar actores</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="actor">Gestion actores</a>
          </li>
          <?php endif ?>
    </ul>
  </div>
</nav>
<div id="cont">
  


