<?php require './templates/tareas/header.phtml'; ?>
<body>
<div class="mt-5 w-25 mx-auto" style="height: 300px;">
    <form method="POST" action="autorizacion">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="contraseña">contraseña</label>
            <input type="contraseña" required class="form-control" id="password" name="contraseña">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alerta'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Ingresar</button>
    </form>
</div>

<?php  require_once 'templates/tareas/footer.phtml'; ?>