<?php

class marcaLista {

function mostrarJuguetes($marcas) {
    require_once "templates/header.phtml";
    ?>
    <main class="container my-4">
        <section class="juguetes">
            <div class="row">
                <?php 
                foreach ($marcas as $index => $marca) { 
                ?>
                    <div class="col-md-4 mb-4">
                        <div class="card">
                        <img src="<?php echo htmlspecialchars($marca->img); ?>" class="card-img-top" alt="<?php echo htmlspecialchars($marca->id_marca); ?>">

                            <div class="card-body">
                                <h5 class="card-title"><?php echo htmlspecialchars($marca->origen); ?></h5>
                                <p class="card-text"><?php echo htmlspecialchars($marca->caracteristica); ?></p>
                                <a href="juguete/<?php echo $index; ?>" class="btn btn-outline-primary me-2">Leer más</a>
                                <?php if (Autorizacion::esAdministrador()) { ?>
                                <a href="actualizarJuguete/<?php echo $marca->id_marca; ?>" class='btn btn-success me-2'>Modificar</a>
                                <a href="eliminarJuguete/<?php echo $marca->id_marca; ?>" class='btn btn-danger'>Eliminar</a>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                <?php 
                } 
                ?>
            </div>
        </section>
    </main>
    <?php
    require_once "templates/mostrar/footer.phtml";
}

function mostrarJuguete($id) {
    require_once "templates/header.phtml";

    // Verificar si el juguete existe
    $marca = seleccionarJuguete($id);
    if (!$marca) {
        echo "<p>Juguete no encontrado.</p>";
        require_once "templates/footer.php";
        return;
    }

    ?>
    <main class="container my-4">
        <section class="juguete">
            <div class="card" style="width: 18rem;">
                <h1><?php echo htmlspecialchars($marca->id_marca); ?></h1>
                <p class="lead mt-3"><?php echo htmlspecialchars($marca->origen); ?></p>
                <a href="#" class="btn btn-primary mb-2">Comprar</a>
                <img class="juguete-image img-fluid" src="<?php echo htmlspecialchars($marca->caracteristica); ?>" alt="Imagen del juguete">
            </div>
        </section>
    </main>
    <?php
    require_once "templates/footer.phtml";
    }
}
